# Project config #
project_name: 'Image-segmentation-tutorial'
log_level: INFO

# Worker config #
# Additional definition for the worker can be found here: https://docker-py.readthedocs.io/en/stable/containers.html

num_gpus: 1

worker:
  image: ranasac/image_segmentation:gpu  # name of your customized images
  volumes:
    /home/ubuntu/atlas_tutorials/Image-segmentation-tutorial/data:     # change this path to your absolute local path of data folder
      bind: /data
      mode: rw